database:
  charset: utf8mb4
  db_name: apiautotest
  host: localhost
  password: '123456'
  port: 3306
  ssh_server:
    mysql_container: mysql8
    password: '123456'
    port: 22
    privat_passowrd: null
    private_key_file: null
    sql_data_file: backup_sqls/
    username: root
  user: root
email:
  addressees:
  - 收件人邮箱1
  - 收件人邮箱2
  contents: 解压apiAutoReport.zip(接口测试报告)后，请使用已安装Live Server 插件的VsCode，打开解压目录下的index.html查看报告
  enclosures: report.zip
  host: smtp.163.com
  password: ASGCSFSGS
  title: 接口自动化测试报告(见附件)
  user: 123456.com
expires: 1648119881370
file_path:
  log: log/run{time}.log
  report: report/
  test_case: data/case_data.xls
request_headers:
  Accept-Encoding: gzip, deflate
  Accept-Language: zh-CN,zh;q=0.9
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/86.0.4240.198 Safari/537.36
server:
  dev: null
  test: https://cvapiconftest.263.net
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjdl9vcGVuYXBpIiwiY3VzdG9tZXJfaWQiOiJVMTAwMDAyNDc4OTIiLCJpYXQiOjE2NDgxMTI2ODEsImV4cCI6MTY0ODExOTg4MX0.waMEouaYXbuYeOl34VX6ydg6cr28f5ofsWMH-vwkDB8
